### ISSUE TITLE
EPIC: Namespacing of experiments

### ISSUE THREAD

**Issue by dannyfriar** [G-Research/fasttrackml#83]
### Use cases
- multiple users share an instance of FastTrackML
- a user wants to partition its experiments/runs/metrics in a different space but keep them all under a unique instance of FastTrackML

### How
In order to achieve this, we want to add a suffix to the tracking URI that effectively partitions the experiments into different namespaces. The 2 UIs and their respective APIs will thus be _prefixed_ by `/ns/<namespace>/` to access a different namespace than the default one.

### Example
A server is started on localhost:5000 and the tracking URI for the default namespace is thus `http://localhost:5000`. The MLFlow client will hit it to create experiments, runs, etc. The UI chooser is available on `http://localhost:5000/`, the MLFlow UI is available on `http://localhost:5000/mlflow/`, and the Aim UI is available on `http://localhost:5000/aim/`. The actual API endpoints are under `http://localhost:5000/(ajax-)api/2.0/mlflow/` for MLFlow and `http://localhost:5000/aim/api/` for Aim.
All the calls towards these endpoints will use the default namespace and thus filter the experiments/runs/etc. based on that.

A namespace called `ns1` is created. The tracking URI to use it is `http://localhost:5000/ns/ns1`, and the UIs are all available under `http://localhost:5000/ns/ns1/` (e.g. Aim is on `http://localhost:5000/ns/ns1/aim/`). The actual API endpoints are under `http://localhost:5000/ns/ns1/(ajax-)api/2.0/mlflow/` for MLFlow and `http://localhost:5000/ns/ns1/aim/api/` for Aim. All the calls towards these endpoints will use the namespace `ns1` and thus filter the experiments/runs/etc. based on that.

---

- [x] Schema: create new table "namespaces" and reference it in the "experiments" table (foreign key - required)
- [x] Schema: add default namespace to the table
- [x] Add middleware that maps `/ns/<namespace>/` to a namespace and adds it to the fiber context — when there is no prefix, set the namespace to the default one
- [x] Adapt all endpoints to fetch the namespace from the context and use it to restrict the queries
  - [x] #203
  - [x] #204
- [x] Adapt both UIs to adapt their API path to include the namespace (if not the default)
  - [x] MLFlow
  - [x] Aim
- [x] #201
- [x] #202

**Comment by dave-gantenbein** [comment]
Feature is complete, future bugs will be tracked as one-off. See 0.4 series for preview release.
