### ISSUE TITLE
EPIC: User management phase 2

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/fasttrackml#988]
Building on the MVP established in #978 add pages to the UI to support user management

- [ ] Authenticated admin users are presented with a link to the application configuration page (only user management is available for now)
- [ ] List all users in the system (list is paginated and loaded async)
- [ ] Edit user page
- [ ] Users can reset their password via the UI
